# This file was generated by GoReleaser. DO NOT EDIT.
cask "dblab" do
  version "0.50.0"

  on_macos do
    on_arm do
      sha256 "0a62df105b0ead60b3a3de229674e0dc85d32aaa0cda4cdd2d4d5e564bf6f67c"
      url "https://github.com/danvergara/dblab/releases/download/v#{version}/dblab_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9bfcd53d431729a271eeee5d4184ab0827447eafc9967a3237b3d0b313bd7347"
      url "https://github.com/danvergara/dblab/releases/download/v#{version}/dblab_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e64faec296abe3c3261e61797080c9afff61fa69f6bceab0c7536658ee78b01c"
      url "https://github.com/danvergara/dblab/releases/download/v#{version}/dblab_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6f8ae24bda660254a357dbfc135bb3d2b8bad2b413554aa13f3dfd4750216e71"
      url "https://github.com/danvergara/dblab/releases/download/v#{version}/dblab_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dblab"
  desc "Interactive client for PostgreSQL, MySQL, SQLite, Oracle, and SQL Server"
  homepage "https://github.com/danvergara/dblab"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dblab"

  # No zap stanza required
end
