# This file was generated by GoReleaser. DO NOT EDIT.
cask "dblab" do
  name "dblab"
  desc "Interactive client for PostgreSQL, MySQL, SQLite, Oracle, and SQL Server"
  homepage "https://github.com/danvergara/dblab"
  version "0.34.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dblab"

  on_macos do
    on_intel do
      url "https://github.com/danvergara/dblab/releases/download/v#{version}/dblab_#{version}_darwin_amd64.tar.gz"
      sha256 "0f474168f79089a7ed5ccc7d5b17dad7274a3358e046f19aa4b638875a2d58bb"
    end
    on_arm do
      url "https://github.com/danvergara/dblab/releases/download/v#{version}/dblab_#{version}_darwin_arm64.tar.gz"
      sha256 "29d47404d91eb3577dbf0c2cfe34aa049b25213b9cb49d50ff520618db61629f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danvergara/dblab/releases/download/v#{version}/dblab_#{version}_linux_amd64.tar.gz"
      sha256 "b284a183e58111d3e86578f21f74c4f1ae94d36507a33deb862b5b142e5e6d75"
    end
    on_arm do
      url "https://github.com/danvergara/dblab/releases/download/v#{version}/dblab_#{version}_linux_arm64.tar.gz"
      sha256 "6e96f13b34f63fa3ba03869f3c285857b3cc52c928869d915f26578a4dc266a8"
    end
  end

  # No zap stanza required
end
