# This file was generated by GoReleaser. DO NOT EDIT.
cask "dblab" do
  version "0.47.2"

  on_macos do
    on_intel do
      sha256 "3cfb7f5ee6c9b9bbcda8f689691b4d05569a2d3961f8fc066b84b3f72dffdfa1"
      url "https://github.com/danvergara/dblab/releases/download/v#{version}/dblab_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2e8d186755618508aef1186cfb76e0bb303a53b9a86e23144fc698f8794a2afc"
      url "https://github.com/danvergara/dblab/releases/download/v#{version}/dblab_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "95391a05ba7d6e64a60192906589a7164a4ef822d4a19e0f0017c56483da09d4"
      url "https://github.com/danvergara/dblab/releases/download/v#{version}/dblab_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cdea28f8d02bf87ba2ce0ab6ab658a99ab47e57efdf7b2c72d832b3b70e180a6"
      url "https://github.com/danvergara/dblab/releases/download/v#{version}/dblab_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dblab"
  desc "Interactive client for PostgreSQL, MySQL, SQLite, Oracle, and SQL Server"
  homepage "https://github.com/danvergara/dblab"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dblab"

  # No zap stanza required

end
