# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seeder < Formula
  desc "Database seeds. CLI and Golang library"
  homepage "https://github.com/danvergaran/seeder"
  version "0.2.8"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danvergara/seeder/releases/download/v0.2.8/seeder_0.2.8_Darwin_x86_64.tar.gz"
      sha256 "76e4d8d5dccff703e219e2886e17edce40a507c34c137d5f53ac8f7d76c83faa"
    end
    if Hardware::CPU.arm?
      url "https://github.com/danvergara/seeder/releases/download/v0.2.8/seeder_0.2.8_Darwin_arm64.tar.gz"
      sha256 "dffd46cd7541685889e13ab962c8023e19243ad0f2fe04640a1dfc59d93eb54a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/danvergara/seeder/releases/download/v0.2.8/seeder_0.2.8_Linux_x86_64.tar.gz"
      sha256 "43ae520223870c0e1e97e0f7dfa7a56d901d89a4f982509fa5e13d01db99e367"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danvergara/seeder/releases/download/v0.2.8/seeder_0.2.8_Linux_arm64.tar.gz"
      sha256 "f2c7e1c56e3cae9e5e6bc6afda270b09e425b5b293d7435abc3f23604bfe01be"
    end
  end

  depends_on "git"
  depends_on "go"

  def install
    bin.install "seeder"
  end
end
