# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seeder < Formula
  desc "Database seeds. CLI and Golang library"
  homepage "https://github.com/danvergaran/seeder"
  version "0.2.9"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danvergara/seeder/releases/download/v0.2.9/seeder_0.2.9_darwin_amd64.tar.gz"
      sha256 "398c026a00bbc7308ae1d505f706b776bb12c70cc4fd5cb7bd622b8619649f28"
    end
    if Hardware::CPU.arm?
      url "https://github.com/danvergara/seeder/releases/download/v0.2.9/seeder_0.2.9_darwin_arm64.tar.gz"
      sha256 "28cbea9ee9df64b5896c5af5759c805fa6bb571a1d2393b6fb96ca79c8a04083"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/danvergara/seeder/releases/download/v0.2.9/seeder_0.2.9_linux_amd64.tar.gz"
      sha256 "9f841695bf842480bef0086721f53cc0227af5e54f3c30ac67f0440279d9bbf8"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danvergara/seeder/releases/download/v0.2.9/seeder_0.2.9_linux_arm64.tar.gz"
      sha256 "25e00eaecba46ab67488293c01958b9c09f00c5c69e9770735eabd17dbf080a5"
    end
  end

  depends_on "git"
  depends_on "go"

  def install
    bin.install "seeder"
  end
end
